### PR TITLE
Adding REPL

### LINKED ISSUE #211: Allow runners to also execute arbitrary code
This would allow the implementation of Repls into the platforms.

### PR DESCRIPTION
**Pull request by flbulgarelli**
Fixes #211

This adds a REPL for querying extra code and own solution within Mumuki. This removes the need of testing code on desktop tool - although it may still be desirable. 

This is enabled only for languages whose runner support it - currently only Haskell

### CODE REVIEW

**Comment by flbulgarelli** [comment]
screencapture-localhost-3000-exercises-5-1440883986806


screencapture-localhost-3000-exercises-5-1440883902370

**Comment by flbulgarelli** [comment]
@faloi @aguspina @mmatos

**Comment by flbulgarelli** [comment]
PS:  There are many JS code smells. 

JS codebase has actually grown a lot, and we need to modularize it. Such issues will be addressed in another branch: https://github.com/mumuki/mumuki-platform/tree/refactor-modular-js

**Comment by faloi** [comment]
* If I don't get it wrong, you are not including the extra code, right?
* We should work on the console's affordance, it doesn't look like something you can interact with. Perhaps a dark blue background could help.

**Comment by flbulgarelli** [comment]
>If I don't get it wrong, you are not including the extra code, right?

No, we are submitting it. See https://github.com/mumuki/mumuki-platform/pull/287/files#diff-113e49f01c07c6b5453e015d712ee34eR10

**Comment by flbulgarelli** [comment]
> We should work on the console's affordance, it doesn't look like something you can interact with. Perhaps a dark blue background could help.

What about a message like  "you can type expressions here"?  Or a thin border?

Many online REPLs don't have dark background. See https://tryhaskell.org/  for instance.

**Comment by faloi** [comment]
> What about a message like "you can type expressions here"? Or a thin border?
>
> Many online REPLs don't have dark background. See https://tryhaskell.org/ for instance.

**Comment by flbulgarelli** [comment]
@faloi Yes there is a thick grey cursor :smile:

**Pull request merged**
