### PR TITLE
Feature no submissions

### PR DESCRIPTION
**Pull request by flbulgarelli**
This PR replaces the submissions model with a new solutions model. It is not just a rename: a user has many submissions for each exericise, but only one solution for each exercise. This means the solution is the current state of an exercise for a given user. 

The motivation behind this change is twofold: 

* reduce storage in ≃ 0.75 factor 
* simplify platform model

### CODE REVIEW

**Comment by flbulgarelli** [comment]
@aguspina @faloi Please review

**Comment by faloi** [comment]
Is this just a rename?

**Comment by aguspina** [comment]
Don't think so, I believe he only keeps the last submission/solution of a user for each exercise

**Comment by aguspina** [comment]
It's ok for me @faloi

**Comment by faloi** [comment]
Ok for me too. 

However, it would be nice if you can write something about the `EventSubscriber`. I imagine submissions are now stored somewhere else using this mechanism, and I'm interested on that.

**Comment by flbulgarelli** [comment]
OK. You mean an explanation here or you want a blog post?

**Comment by faloi** [comment]
A blog post should be really, really nice!

**Comment by flbulgarelli** [comment]
@faloi OK. But In the meanwhile:

* Submissions are not stored in the platform. But...
* we have event subscribers now, which listen to platform events - currently only submissions. We can register another service for storing submissions. That is why we now have https://github.com/mumuki/mumuki-event-tracker, which is up and runnig since a few days ago.

**Comment by flbulgarelli** [comment]
PS: I have already migrated all the production submissions to the new storage :smile:

**Comment by PalumboN** [comment]
:cool:

**Pull request merged**
