### PR TITLE
Feature remove fb and twitter plugins

### PR DESCRIPTION
**Pull request by flbulgarelli**

### CODE REVIEW

**Comment by faloi** [comment]
Can you provide a screenshot? :sweat_smile:

**Comment by flbulgarelli** [comment]
screencapture-localhost-3000-exercises-5-1440886073407

**Comment by flbulgarelli** [comment]
@faloi Done

**Comment by faloi** [comment]
Veri _biutiful_, you really are a box of surprises. Only one suggestion: what do you think about preserving the brand color on the favicon?

**Comment by flbulgarelli** [comment]
Hmm, no. 

Most -well designed - sites  nowadays don't keep social networks colors, since they most of the times they break the color scheme of the site. See Airbnb, codeschool, etc

**Pull request merged**
