### PR TITLE
Issue #207 submission single page

### LINKED ISSUE #154: Show the actual result of a past submission
When browsing past submissions for an exercise you see the code for that submission, but the result shown is not always the one corresponding to that submission.

If you open the submission in a new tab it behaves as expected and shows the result for that submission, but if you open it in the same tab it goes crazy, shows different things at first and then stabilizes on a result that may not be the one for that submission.

### LINKED ISSUE #204: The loading spinner goes funny after the submission
It happens after you submit, while you're waiting for the result. Sometimes there are some blinks too.

### LINKED ISSUE #207: Test result in the same page as the code, below the exercise description
I think the current approach is very old school: fill a form, submit and wait for the result to show.

My proposal is to have everything in the same page, and update the results every time the user submits a new version of the code.

### PR DESCRIPTION
**Pull request by flbulgarelli**
Fixes #207 
Closes #204 
Closes #154 
Related to #102

### CODE REVIEW

**Comment by flbulgarelli** [comment]
Output sample when everything is on Haskell
submission_all_ok

**Comment by flbulgarelli** [comment]
Output sample when tests failed (Haskell)

submission_tests_failed

**Comment by flbulgarelli** [comment]
Sample output for pending submission (progress icon is animated)

submission_pending

**Comment by faloi** [comment]
Mmm, is the panel completely necessary? 

I think the "Results" label plus the status icon (passed, failed) or a "Loading" with the spinner would be enough.

**Comment by flbulgarelli** [comment]
Finally, with warnings:

submission_tests_passed_with_warnings

**Comment by flbulgarelli** [comment]
@faloi I think the panel is not necessary but helpful:

* It allows to delimit the results
* It allows to use more explicit colors
* It is a consistent manner of displaying results
* RubyMonk does :stuck_out_tongue: 
* I have just changed the "results" title to actually show something more descriptive like:
    * Worked, but you can do it better
    * Oops, something went wrong
    * All right

Regarding the last item, I have used the tools with non-tech people and they found not obvious that "passed" meant "your submission is ok", or even they did not notice the green check. That is why I think we should make it more aggresive

**Comment by faloi** [comment]
It would be nice to disable the _Send_ button until the response is received, to prevent multiple submissions

**Comment by jvillarejo** [comment]
I think there is to much overhead on the same page, I agree with @faloi  that the send button should be disable. 

Also is it correct that the next and before button are visible when the submission failed? 

Other thing, related information should be together, the report button should be smaller and besides the exercise assignment

**Comment by flbulgarelli** [comment]
Yes, there is a pending refactor of those three buttons. I know they are not in the best place and size, but please ignore them for purpouse of this PR. 

Send should be disabled, i agree. 

But I am interesed in the overhead issue: We wanted to have a single page with excercise descrption, editor and results. This is more dynamic and I agree it's better and more interactive - I myself enjoyed a bit more sending exercises :stuck_out_tongue: 

Buuuut....

**Comment by jvillarejo** [comment]
We as developers have a biased point of view. A/B testing is the way. I'll think of a better page organization in the meantime

**Comment by flbulgarelli** [comment]
Stupid sexy A/B testing....

**Comment by asanzo** [comment]
Hell yeah. I love this way to present results. I must say I found the colors and the size of the result a bit too harmful for the eye. But on the other hand, I think that a pretty big green "¡Yay! GOOD" is very motivating.... When tests fail, I'd just disable the buttons as said above, and put a little bit of red/orange/yellow as feedback.

**Comment by flbulgarelli** [comment]
Ok, perhaps the problem of clumsiness is just... that we have too much information and it is not well presented. 

What about the following - sample sample that previous use case, but with some changes?

alt_minimalist_design

In order to introduce guide context, we coul just introduce a navbar (left, botton or top)

**Comment by flbulgarelli** [comment]
This is how it looks now

**Comment by faloi** [comment]
Please @jvillarejo help me convince @flbulgarelli to drop that ugly panel!

**Comment by flbulgarelli** [comment]
Haha, I don't wanna get convinced of that - I know it can be better -, just gimme a better design and I would apply happily :smile:

**Comment by faloi** [comment]
This is my version, using something bootstrap calls "callout":

image

**Comment by flbulgarelli** [comment]
Love it!

**Pull request merged**
