### PR TITLE
Fixing facebook profile picture

### LINKED ISSUE #277: Use better Facebook profile pictures
The quality is pretty bad, I imagine Facebook can provide something better. See comparison below.

|Facebook|GitHub|
|:-:|:-:|:-:|
|image|image|

### PR DESCRIPTION
**Pull request by gcrespi**
fixes #277, (couldn't test it in a local server so at least I hope so...)

### CODE REVIEW

**Comment by flbulgarelli** [comment]
@gcrespi Merged. Now please test in stg after Travis finished build

**Comment by aguspina** [comment]
@flbulgarelli are u sure we have an facebook staging app?

**Comment by flbulgarelli** [comment]
Yes, we have!

But perhaps I need to add your FB users as tester accounts to the app.

**Comment by aguspina** [comment]
Yes, please add us!

**Comment by flbulgarelli** [comment]
Done

**Pull request merged**
