### PR TITLE
Issue #216 inline editor

### LINKED ISSUE #201: Make submission editor affix
That way the user does not need to scroll up after reading a long description.

### LINKED ISSUE #216: Inline editor
@asanzo suggested in #207 to have editor inlined, as in RubyMonk. I have tested the idea, and I have got mixed results. In some cases, particullary when the description is mostly text and a bit of code, I think that the proposed layout is better. 

new_design_ok

But in other scenarios, when you have more code and/or images, the results are worse:

new_design_nok

new_design_nok2

You can notice large blank areas.

Since exercise description is just markdown, which does not have any directive for grids or layouts, it is not actually possible to change it from within description. Changing from css it is technically possible, but results of a transformation may be semantically broken since you wont't have any idea where image description will appear. 

I have no real solution for this. I would like to hear your comments @asanzo, @faloi

### PR DESCRIPTION
**Pull request by flbulgarelli**
Fixes #216 
Closes #201

### CODE REVIEW

**Comment by faloi** [comment]
A nice convention I've used in another projects is to include a screenshot when the changes involves the UI, because many of us don't have the ability of rendering HTML in our heads. :stuck_out_tongue: 

(ok, I could checkout your branch locally... but that decreases my will of looking at your PR)

**Comment by flbulgarelli** [comment]
@faloi please check the discussion in the issue. I put the screeshot there

**Comment by faloi** [comment]
Do you have an example of the markdown syntax?

**Comment by flbulgarelli** [comment]
Yes:

| tablero inicial  |      |  tablero final  |
|:--:|:--:|:--:|
|3x3h |<i class="fa fa-arrow-right"></i> |3x3h01|

**Comment by faloi** [comment]
Great, I've used that before... always with the help of http://www.tablesgenerator.com/markdown_tables#

**Pull request merged**
